In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [ ]:
# Add bias term to the dataset
def add_bias(X):
   return np.c_[np.ones((X.shape[0], 1)), X]
# Train perceptron function
def train_perceptron(X, y, epochs=1000, learning_rate=0.1):
    weights = np.zeros(X.shape[1])  # Initialize weights
    for epoch in range(epochs):
        for i in range(len(X)):
            if y[i] * np.dot(X[i], weights) <= 0:
                weights += learning_rate * y[i] * X[i]
    return weights

# Binary perceptron prediction function
def predict_perceptron(X, weights):
    activations = np.dot(X, weights)
    return np.where(activations >= 0, 1, -1)

# Generate binary classification dataset
X, y = make_classification(n_samples=500, n_features=5, n_classes=2, random_state=42)
X = add_bias(X)  # Add bias column
y = np.where(y == 0, -1, 1)  # Convert to -1 and 1 for perceptron

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
learning_rates = [0.01, 0.05, 0.1, 0.2]
epochs = [500, 1000, 1500]

# Train perceptron
for i in range(len(epochs)):
  for j in range(len(learning_rates)):
    weights = train_perceptron(X_train, y_train, epochs[i], learning_rates[j])
    print(f"Training with epochs={epochs[i]} and learning_rate={learning_rates[j]}")
    # Predict and evaluate
    y_pred = predict_perceptron(X_test, weights)
    print("Binary Perceptron Accuracy:", accuracy_score(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))

Training with epochs=500 and learning_rate=0.01
Binary Perceptron Accuracy: 0.8
[[40 13]
 [ 7 40]]
              precision    recall  f1-score   support

          -1       0.85      0.75      0.80        53
           1       0.75      0.85      0.80        47

    accuracy                           0.80       100
   macro avg       0.80      0.80      0.80       100
weighted avg       0.81      0.80      0.80       100

Training with epochs=500 and learning_rate=0.05
Binary Perceptron Accuracy: 0.8
[[40 13]
 [ 7 40]]
              precision    recall  f1-score   support

          -1       0.85      0.75      0.80        53
           1       0.75      0.85      0.80        47

    accuracy                           0.80       100
   macro avg       0.80      0.80      0.80       100
weighted avg       0.81      0.80      0.80       100

Training with epochs=500 and learning_rate=0.1
Binary Perceptron Accuracy: 0.8
[[40 13]
 [ 7 40]]
              precision    recall  f1-score   supp

In [ ]:
# Softmax
def softmax(z):
    exp_z = np.exp(z - np.max(z))
    return exp_z / np.sum(exp_z)

# Multiclass perceptron training function using softmax
def train_multiclass_softmax(X, y, num_classes, epochs, learning_rate):
    weights = np.zeros((num_classes, X.shape[1]))  # Initialize weights
    for epoch in range(epochs):
        for i in range(X.shape[0]):  # Loop over each sample
            xi = X[i]
            yi = y[i]
            # Compute logits (for all classes) and probabilities
            logits = np.dot(weights, xi)
            probabilities = softmax(logits)

            # Convert label to one-hot encoding
            y_one_hot = np.zeros(num_classes)
            y_one_hot[yi] = 1

            # Update weights for each class
            for k in range(num_classes):
                gradient = (probabilities[k] - y_one_hot[k]) * xi  # Gradient for class k
                weights[k] -= learning_rate * gradient
    return weights

    # Prediction function for multiclass perceptron using softmax
def predict_multiclass_softmax(X, weights):
    logits = np.dot(X, weights.T)  # Compute logits for each class
    probabilities = softmax(logits)  # Apply softmax to compute class probabilities
    return np.argmax(probabilities, axis=1)  # Return the class with highest probability

### Multiclass Perceptron Dataset

In [ ]:
 # Generate multiclass dataset
X, y = make_classification(n_samples=500, n_features=5, n_classes=3, n_informative=3, random_state=42)

In [ ]:
X = add_bias(X)

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)

def predict_multiclass_softmax(X, weights):
    logits = np.dot(X, weights.T)  # Compute logits for each class
    probabilities = softmax(logits)  # Apply softmax to compute class probabilities
    return np.argmax(probabilities, axis=1)  # Return the class with highest probability

In [ ]:
learning_rates = [0.01, 0.05, 0.1, 0.2]
epochs_list = [500, 1000, 1500]

for i in range(len(epochs)):
  for j in range(len(learning_rates)):
    # Train multiclass perceptron
    num_classes = len(np.unique(y_train))  # Number of unique classes in y_train
    weights_softmax = train_multiclass_softmax(X_train, y_train, num_classes, epochs=1000, learning_rate=0.1)
    # Predict and evaluate
    y_pred_softmax = predict_multiclass_softmax(X_test, weights_softmax)
    print("Multiclass Perceptron with Softmax Accuracy:", accuracy_score(y_test, y_pred_softmax))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_softmax))
    print(classification_report(y_test, y_pred_softmax))

Multiclass Perceptron with Softmax Accuracy: 0.64
Confusion Matrix:
 [[22  6  0]
 [17 12  5]
 [ 3  5 30]]
              precision    recall  f1-score   support

           0       0.52      0.79      0.63        28
           1       0.52      0.35      0.42        34
           2       0.86      0.79      0.82        38

    accuracy                           0.64       100
   macro avg       0.63      0.64      0.62       100
weighted avg       0.65      0.64      0.63       100

Multiclass Perceptron with Softmax Accuracy: 0.64
Confusion Matrix:
 [[22  6  0]
 [17 12  5]
 [ 3  5 30]]
              precision    recall  f1-score   support

           0       0.52      0.79      0.63        28
           1       0.52      0.35      0.42        34
           2       0.86      0.79      0.82        38

    accuracy                           0.64       100
   macro avg       0.63      0.64      0.62       100
weighted avg       0.65      0.64      0.63       100

Multiclass Perceptron with